spring:
  application:
    name: auth-service
  datasource:
#    mysql source for running it as containerize app
#    url: jdbc:mysql://mysqldb8/ecommerce_user?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Manila
#    mysql source for local
    url: jdbc:mysql://localhost:3306/ecommerce_user?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Manila
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  zipkin:
#    base-url: http://localhost:9411/
#    sender:
#      type: rabbit

server:
  port: 8081

jwt:
  secret: secret
  jwtExpirationMs: 86400000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka






