server:
  port: 8080

spring:
  application:
    name: ecommerce-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  secret: secret
  jwtExpirationMs: 86400

# Disable accessing services using service name (i.e. gallery-service).
# They should be only accessed through the path defined below.
# Link: https://stackoverflow.com/questions/46317388/zuul-service-name-exposed-instead-of-route-path-only
zuul:
  ignoredServices: "*"
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000


# A prefix that can added to beginning of all requests.
#zuul.prefix=/api
  
  # Map paths to services
#  zuul.routes.gallery-service.path=/gallery/**
#  zuul.routes.gallery-service.service-id=gallery-service
  
  # Map path to auth service
#  zuul.routes.auth-service.path=/auth/**
#  zuul.routes.auth-service.service-id=AUTH-SERVICE
  
  # By default, all requests to gallery service for example will start with: "/gallery/"
  # What will be sent to the gallery service is what comes after the path defined, 
  # So, if request is "/gallery/view/1", gallery service will get "/view/1".
  # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
#  zuul.routes.auth-service.strip-prefix=false
  
  # Exclude authorization from sensitive headers
#  zuul.routes.auth-service.sensitive-headers=Cookie,Set-Cookie
