spring:
  application:
    name: order-service
  datasource:
    #    mysql source for running it as containerize app
    #    url: jdbc:mysql://mysqldb8/ecommerce_order?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Manila
    #    mysql source for local
    url: jdbc:mysql://localhost:3306/ecommerce_order?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Manila
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9096