server:
  port: 8085

spring:
  application:
    name: ecommerce-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  ignored-services: "*"
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    inventory-service:
      path: /inventory/**
      serviceId: INVENTORY-SERVICE
      strip-prefix: false
    auth-service:
      path: /auth/**
      serviceId: AUTH-SERVICE
      strip-prefix: false
    order-service:
      path: /order/**
      serviceId: ORDER-SERVICE
      strip-prefix: false
    cart-service:
      path: /cart/**
      serviceId: CART-SERVICE
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 40000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000


jwt:
  secret: secret
