spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_inventory?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Manila
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  zipkin:
#    base-url: http://localhost:9411/
#    sender:
#      type: rabbit

server:
  port: 9095

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka






