spring:
  application:s
    name: cart-service
  datasource:
#    mysql source for running it as containerize app
    url: jdbc:mysql://mysqldb8/ecommerce_cart?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Manila
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit

server:
  port: 8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka






