name: Java CI with Maven

on:
  pull_request:
    branches: ["develop"]
  push:
    branches: [ "feature/auth-service" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Install ecommerce-common dependency
        run: mvn install
        working-directory: ecommerce-commons
      - name: Build & test auth-service
        run: mvn -B package --file pom.xml
        working-directory: auth-service